version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myApp
hooks:
  ApplicationStop:
    - location: scripts/applicationStop.sh
  AfterInstall:
    - location: scripts/afterInstall.sh